### ISSUE TITLE
All masks are black

### ISSUE THREAD

**Issue by tax313** [wuhuikai/GP-GAN#1]
Dear authors,

Thanks for the awesome work! The results are very impressive. I just found that all (or some) masks in the in the folder [mask](https://github.com/wuhuikai/GP-GAN/blob/master/mask/cropped_masks/00000064/tree_2.png) are black. Could you correct them? Thanks.

**Comment by wuhuikai** [comment]
They’re not black actually. But the value of the masks is 1 in 0-255 images, so they look like black images.
