### ISSUE TITLE
How to make the mask? 

### ISSUE THREAD

**Issue by Andreas-Sujono** [wuhuikai/GP-GAN#11]
The mask that each pixel has value 0 or 1 , how to make such mask

**Comment by wuhuikai** [comment]
1. Make a black-white mask
2. divide by `255`

**Comment by ghost** [comment]
photoshop

**Comment by weizhou1001** [comment]
![cones](https://user-images.githubusercontent.com/48662491/125379008-17b0cf00-e3d3-11eb-8189-4482104db434.png)
Hi, This is a mask I made. The background is 0, the object is 1. It looks the same as the sample mask, but it doesn't work when I tried to use it.. any ideas why this didn't work? The code i used to convert mask is
` image = cv2.imread('images/cone17.jpg')
    label = cv2.imread('labels/cone17 - safety_cones.png')
    mask = np.zeros(image.shape, dtype=np.uint8)
    idx = np.nonzero(label)
    mask[idx[0], idx[1], idx[2]] = 1`

**Comment by wuhuikai** [comment]
Can you show me the error message or results?

**Comment by weizhou1001** [comment]
![src](https://user-images.githubusercontent.com/48662491/125393781-e85a8c00-e3eb-11eb-99e1-83929c59fc04.jpg)
![target](https://user-images.githubusercontent.com/48662491/125393818-f90b0200-e3eb-11eb-8c64-39d0997dca98.jpg)
Above are the src and target images. Mask is in previous comment. The result image I got is 

![results](https://user-images.githubusercontent.com/48662491/125393870-14760d00-e3ec-11eb-852e-bd78d7ed1a13.png)
The src cones didn't seem to be blended into the target image

**Comment by wuhuikai** [comment]
Can you visualize the mask with black and white ?

**Comment by weizhou1001** [comment]
![label_screenshot_13 07 2021](https://user-images.githubusercontent.com/48662491/125400358-21e3c500-e3f5-11eb-9cab-dfb36917cb4c.png)
above is label * 255

**Comment by wuhuikai** [comment]
Try to use label as mask directly

**Comment by weizhou1001** [comment]
"above is label * 255"   the label here is the one uploaded in the previous reply 

> ![cones](https://user-images.githubusercontent.com/48662491/125379008-17b0cf00-e3d3-11eb-8189-4482104db434.png)
> Hi, This is a mask I made. The background is 0, the object is 1. It looks the same as the sample mask, but it doesn't work when I tried to use it.. any ideas why this didn't work? The code i used to convert mask is
> ` image = cv2.imread('images/cone17.jpg') label = cv2.imread('labels/cone17 - safety_cones.png') mask = np.zeros(image.shape, dtype=np.uint8) idx = np.nonzero(label) mask[idx[0], idx[1], idx[2]] = 1`

Do you mean this label?

**Comment by wuhuikai** [comment]
`
image = cv2.imread('images/cone17.jpg')
mask = cv2.imread('labels/cone17 - safety_cones.png')
`

**Comment by weizhou1001** [comment]
![image](https://user-images.githubusercontent.com/48662491/125542303-63873205-0f34-4cbd-8f6b-ac23ac789fa7.png)
This is the result we got.. we tried changing the opacity, but still got similar results.. 
anyway it worked. but the label is not 0 or 1 format.

**Comment by wuhuikai** [comment]
You can convert it to [0, 1] format and then try to adjust color weight.

**Comment by weizhou1001** [comment]
Any chance you could write a read me file for creating masks? Or a standard step to creat customised masks? It seems not very clear what format can be used, what cannot.

**Comment by wuhuikai** [comment]
masks with 0 and 1
