### ISSUE TITLE
Problems installing via Docker File

### ISSUE THREAD

**Issue by mowolf** [wuhuikai/GP-GAN#12]
Successfully built the docker container. Running your test script (in docker) or doing `import chainer` in the python3 console results in following output. However importing other installed packages works (like numpy).

`>>> import chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/chainer/__init__.py", line 10, in <module>
    from chainer import backends  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/chainer/backends/__init__.py", line 1, in <module>
    from chainer.backends import cuda  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/chainer/backends/cuda.py", line 45, in <module>
    from chainer.backends import _cpu
  File "/usr/local/lib/python3.5/dist-packages/chainer/backends/_cpu.py", line 8, in <module>
    import chainerx
  File "/usr/local/lib/python3.5/dist-packages/chainerx/__init__.py", line 28, in <module>
    from chainerx.creation.from_data import asanyarray  # NOQA
ImportError: No module named 'chainerx.creation'`

Following the installation for [chainerX](https://docs.chainer.org/en/stable/chainerx/install/index.html) resulted in output that suggests that everything is properly installed.

Did I miss something? I executed following command in the docker image:
`python3 run_gp_gan.py --src_image images/test_images/src.jpg --dst_image images/test_images/dst.jpg --mask_image images/test_images/mask.png --blended_image images/test_images/result.png` 

**How I used docker:**
Built the image with `docker image build -t gp-gan:1.0 .`Then I started the container via `docker container run -dit --name gp-gan gp-gan:1.0` and then attached via `docker attach gp-gan`

Any help would be greatly appreciated! :)

**Comment by wuhuikai** [comment]
Did you install the right version of chainer?

**Comment by mowolf** [comment]
chainer 6.3.0 is installed like it is given in the requirements. 
**Package             Version**
chainer             6.3.0
cupy                6.3.0
cupy-cuda92         7.1.0
...

Might it be a problem with cuda, so that the chainer installation is built without it? What docker version and command do you use to start the container?

**Comment by wuhuikai** [comment]
I don't use docker in my experiment. Maybe it's a chainer related issue.

**Comment by mowolf** [comment]
Ok, thanks anyways. I think it is a problem with the cuda version on the host system. If I figure it out I ll post a solution here.
