### ISSUE TITLE
Demo not working anymore?

### ISSUE THREAD

**Issue by Titoine** [wuhuikai/GP-GAN#13]
Hi,
It seems that demo aren't working. It seems everything went well but we receive a 401 Unauthorized when the image is requested.

![image](https://user-images.githubusercontent.com/3514286/75671351-d2c54600-5c7e-11ea-8c97-1872f11f8f48.png)

**Comment by wuhuikai** [comment]
Busy with some deadlines. Stay tuned within a month : )

**Comment by Titoine** [comment]
Nice!
btw I managed to make it works locally.

**Comment by Tylersuard** [comment]
Same!  Would love to use the demo.

**Comment by wuhuikai** [comment]
Will back in two weeks : )

**Comment by Tylersuard** [comment]
Thank you.  I made a Colab version, would you like me to create a pull request and add it?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by wuhuikai** [comment]
@Tylersuard Feel free to create a pull request : ) Thanks for your contribution.

**Comment by wuhuikai** [comment]
@Titoine @Tylersuard Demo is back online now : )
