### ISSUE TITLE
Extension to a new dataset

### ISSUE THREAD

**Issue by DyassKhalid007** [wuhuikai/GP-GAN#14]
I am trying to retrain the trained supervised GP-GAN on a new data-set. I have downloaded the transient attribute data-set but I am kind of lost how to retrain the model on my dataset. I have my src and mask images. Thanks

**Comment by wuhuikai** [comment]
One possible way is:
    1. use `mask` to extract the foreground object  from `src` and do some augmentations such as color/contrast adjustment.
    2. paste the augmented object on `src`, noted as `img`.
    3. use `img` as input, `src` as ground truth.
