### ISSUE TITLE
image width height different causing error

### ISSUE THREAD

**Issue by shiyingZhang90** [wuhuikai/GP-GAN#16]
Hi @wuhuikai ,
I have image with 600x799, and  I initially just not modify the image size, and get following error:
 copy_paste_init = obj_im_pyramid[0] * mask_init + bg_im_pyramid[0] * (1 - mask_init)
ValueError: operands could not be broadcast together with shapes (64,64,4) (64,64,3) 

Then due to there is no separate width, height argument, I pass in --image_size=800, and the python execution hangs after it print out input arguments. Any idea what I did wrong?

**Comment by shiyingZhang90** [comment]
Hi @wuhuikai ,
I already solved previous issue by updating my testing photo, yet the result I'm getting is super weird -- the color shifts a lot and it seems not blending two images at all, I thought it's due to mask file initially, so I tried your mask as well, but result is same. Any idea? I attach my result and source as well
![2_result](https://user-images.githubusercontent.com/53356251/80544764-9bb19f00-8966-11ea-83ab-9555afb4a2ab.png)
![2](https://user-images.githubusercontent.com/53356251/80544783-a53b0700-8966-11ea-9474-ebf89f89c301.jpg)

**Comment by wuhuikai** [comment]
1. `--image_size` should be set to 64.
2. The error is caused by the format of your input image, it should be in `RGB` not `RGBA`.
3. Please modify [L205-L214](https://github.com/wuhuikai/GP-GAN/blob/6d1e6e51f4932bd8ba7ea8eccf640555f5c28246/gp_gan.py#L205).

**Comment by GZeta95** [comment]
@shiyingZhang90  How did you solve the size problem?
