### ISSUE TITLE
How to generate mask.png from mask_display.png?

### ISSUE THREAD

**Issue by panovr** [wuhuikai/GP-GAN#17]
Hi,
  there are two images names `mask.png` and `mask_display.png` in the `test_images` folder. It seems that `mask_display.png` is a grayscale image with 0-255 pixel values, and `mask.png` is an index image or label image with 0-1 pixel values. May I ask that how to generate `mask.png` from `mask_display.png`?

**Comment by wuhuikai** [comment]
Divide by 255 : )
