### ISSUE TITLE
PyTorch?

### ISSUE THREAD

**Issue by andrewjong** [wuhuikai/GP-GAN#18]
I know this is a long-shot question, and probably there are no plans for this, but I was wondering if the authors would consider migrating this repository to PyTorch. According to the [website](https://chainer.org/announcement/2019/12/05/released-v7.html), Chainer will no longer be developed and the company behind Chainer is migrating to PyTorch.

No problem if not; GP-GAN is a cool paper and it's wonderful there's even code to support it in the first place.

**Comment by wuhuikai** [comment]
I do **not** have any plan at present.
