### ISSUE TITLE
What's the purpose of laplacian/gaussian_param?

### ISSUE THREAD

**Issue by u10116032** [wuhuikai/GP-GAN#2]
First of all, thanks for the great work which point out a framework for high resolution on GAN!!

But I don't understand what's the purpose of the functions "laplacian_param" and "gaussian_param" in gp_gan.py?

Could you give me some hint?

**Comment by wuhuikai** [comment]
The two functions try to generate laplacian filter and Gaussian filter in 2D Fourier space respectively.

**Comment by u10116032** [comment]
Thanks for the answer, but I still don't know:
1. why do the laplacian and gaussian filter need to be resized and rolled before fft2?
2. why do you divide "(dct2(L[:,:, i]) + color_weight*Xdct)" with param? What's the meaning of the "divide" operation?

**Comment by wuhuikai** [comment]
Please see this paper for details: "A method for enforcing integrability in shape from shading algorithms"

**Comment by u10116032** [comment]
Okay, I'll check this paper, but could you tell me what's the meaning that you do np.roll alone horizontal and vertical in laplacian and gaussian filter? 

Thanks!!

**Comment by wuhuikai** [comment]
Sorry for the late reply. np.roll is used to calc gradients both in horizontal and vertical directions.
