### ISSUE TITLE
mask laplacian pyramid 

### ISSUE THREAD

**Issue by rezhv** [wuhuikai/GP-GAN#22]
In the paper, it is said that you calculate the **Laplacian pyramid for Xmask** and then use its appropriate level to solve the proposed Gaussian-Poisson Equation in every iteration of the for-loop. However, I did not understand why you would need to make the Laplacian pyramid for the mask. It seems like in your implementation too you simply resize the mask and use it in different iterations of the for-loop. (maybe I missed something?)

This is the equation on how you calculate v from the paper. (' u is the discretized divergence of v')

<img width="681" alt="Screen Shot 2020-11-30 at 7 09 27 PM" src="https://user-images.githubusercontent.com/56566565/100692377-92931100-333f-11eb-8919-3331fb2ba546.png">

I'm not sure but I think if you make the pyramid for the mask and use it then you would not merely have 0's and 1's in the mask matrix. So the question is: how would you then calculate v if the mask is not only 1's and 0's? Also I was not able to find where in your code you make the Laplacian pyramid for the mask. Are we doing something different than what the paper says?

**Comment by wuhuikai** [comment]
Paper is cheap, see the code : )
