### ISSUE TITLE
Save a trained model

### ISSUE THREAD

**Issue by supritbansod** [wuhuikai/GP-GAN#25]
Hello Hukai Wu.. The available pretrained model is saved as .npz file. During training for every epoch, separately for generator, discriminator and snapshot a .npz file is getting saved. How to save full trained model in .npz format?

**Comment by wuhuikai** [comment]
Create a subclass of chainer.ChainList with G and D as attributes.

**Comment by supritbansod** [comment]
With the help of chainer.ChainList(G,D) I could save the model, but while loading it is giving an error KeyError: 'encoder/0/W is not a file in the archive'. Also, the arrangement of layers in pretrained model is different than the one obtained from appending G and D model. 
Pretrained Model arrangement (encoder/9/avg_mean encoder/5/W decoder/9/W bn/avg_var encoder/11/W decoder/7/avg_var encoder/9/N encoder/0/W decoder/7/N decoder/1/N encoder/2/W bn/beta encoder/3/N decoder/4/gamma encoder/9/gamma decoder/4/avg_var encoder/6/beta decoder/0/W decoder/3/W decoder/7/gamma decoder/7/beta decoder/10/beta encoder/3/avg_var decoder/10/avg_mean decoder/4/N decoder/4/beta encoder/6/avg_var encoder/3/gamma decoder/1/gamma decoder/10/gamma encoder/3/beta decoder/6/W bn/N decoder/1/beta bn/gamma decoder/4/avg_mean encoder/3/avg_mean decoder/10/avg_var bn/avg_mean encoder/6/N encoder/6/avg_mean decoder/12/W encoder/8/W encoder/9/beta decoder/1/avg_mean encoder/6/gamma decoder/10/N decoder/1/avg_var decoder/7/avg_mean encoder/9/avg_var)

Model with chainer.ChainList(G,D) (0/encoder/0/W 0/encoder/2/W 0/encoder/3/gamma 0/encoder/3/beta 0/encoder/3/N 0/encoder/3/avg_mean 0/encoder/3/avg_var 0/encoder/5/W 0/encoder/6/gamma 0/encoder/6/beta 0/encoder/6/N 0/encoder/6/avg_mean 0/encoder/6/avg_var 0/encoder/8/W 0/encoder/9/gamma 0/encoder/9/beta 0/encoder/9/N 0/encoder/9/avg_mean 0/encoder/9/avg_var 0/encoder/11/W 0/decoder/0/W 0/decoder/1/gamma 0/decoder/1/beta 0/decoder/1/N 0/decoder/1/avg_mean 0/decoder/1/avg_var 0/decoder/3/W 0/decoder/4/gamma 0/decoder/4/beta 0/decoder/4/N 0/decoder/4/avg_mean 0/decoder/4/avg_var 0/decoder/6/W 0/decoder/7/gamma 0/decoder/7/beta 0/decoder/7/N 0/decoder/7/avg_mean 0/decoder/7/avg_var 0/decoder/9/W 0/decoder/10/gamma 0/decoder/10/beta 0/decoder/10/N 0/decoder/10/avg_mean 0/decoder/10/avg_var 0/decoder/12/W 0/bn/gamma 0/bn/beta 0/bn/N 0/bn/avg_mean 0/bn/avg_var 1/0/W 1/2/W 1/3/gamma 1/3/beta 1/3/N 1/3/avg_mean 1/3/avg_var 1/5/W 1/6/gamma 1/6/beta 1/6/N 1/6/avg_mean 1/6/avg_var 1/8/W 1/9/gamma 1/9/beta 1/9/N 1/9/avg_mean 1/9/avg_var 1/11/W)

**Comment by wuhuikai** [comment]
You should load it separately from the pretrained model and then save it as a whole.

**Comment by supritbansod** [comment]
Yes I have separately saved the model by writing `serializers.save_npz('train_blending_gan.npz', chainer.ChainList(G, D))` and then passed this model in the run_gp_gan.py file instead of pretrained model. It is not getting load properly and giving the error. 
Does the model is dependent on input image dimension like (631x472)? Can I provide varying image dimension?

**Comment by wuhuikai** [comment]
1. Then you should load `train_blending_gan.npz` with `chainer.ChainList(G, D))`.
2. No, it's not.

**Comment by supritbansod** [comment]
As per my knowledge, I did not get how to load model with `chainer.ChainList(G,D)` from the documentation. Which command did you use to save and load both blending gan and Wasserstein gan models ?

**Comment by supritbansod** [comment]
I could load model properly. Only generator part is saved with `serializers.save_npz('blending_gan.npz', G)` and it loaded correctly. `chainer.ChainList(G,D)` will save both generator and discriminator, but for train_blending_gan, require generator.

**Comment by wuhuikai** [comment]
```
model = chainer.ChainList(G,D)
model.load...
```
