### ISSUE TITLE
Dataset related to Polar Bear(paper Fig.10)

### ISSUE THREAD

**Issue by jsshin98** [wuhuikai/GP-GAN#27]
Hi, I want to test the model with the polar bear image that you uploaded as Fig.10 in your paper. However, there is no those kinds of sets on Test data. How can I get them?

**Comment by wuhuikai** [comment]
[Here](https://github.com/wuhuikai/DeepJS/tree/master/images/blending_mask) is the polar bear image.

**Comment by jsshin98** [comment]
Thanks!
