### ISSUE TITLE
What is the role of BlendingGAN?

### ISSUE THREAD

**Issue by WuKongy** [wuhuikai/GP-GAN#28]
Hi, I have a question about BlendingGAN.
What is the role of BlendingGAN? 
BlendingGAN aims to produce <a href="https://www.codecogs.com/eqnedit.php?latex=x_{dst}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x_{dst}" title="x_{dst}" /></a>. So why not replace BlendingGAN with <a href="https://www.codecogs.com/eqnedit.php?latex=x_{dst}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x_{dst}" title="x_{dst}" /></a> during the test process, i.e., no need to train the GAN.
Thanks!

**Comment by wuhuikai** [comment]
For the specific dataset, you can. But in general, x_dst and a well-blended image are not the same.

**Comment by WuKongy** [comment]
Thanks!
