### ISSUE TITLE
Pretrained model is not accessible

### ISSUE THREAD

**Issue by akhmedov** [wuhuikai/GP-GAN#29]
Hello! I was tried to look on the performance of pretrained model throw all available links (GitHub and Colab), but it seems the model weights are under private configuration at the moment. Can you help in accessing please?

<img width="1920" alt="Screenshot 2021-11-09 at 16 36 51 (2)" src="https://user-images.githubusercontent.com/13253512/140943885-dddcd490-6556-422e-95da-e31352de1efe.png">

**Comment by JJBT** [comment]
Also faced with this problem. @akhmedov did u solved?

**Comment by wuhuikai** [comment]
https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing

Plase use the above link : )

**Comment by akhmedov** [comment]
Yeap, it's fine. Thank you for the support and project!
