### ISSUE TITLE
Download pretrained model

### ISSUE THREAD

**Issue by embeddedsystemsnu** [wuhuikai/GP-GAN#31]
Dear authors, 
Could you please accept me for the driver link to download pretrained models? 
My email is "hanngoctruc@gmail.com". 
Thank you so much ~

**Comment by wuhuikai** [comment]
https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing

**Comment by embeddedsystemsnu** [comment]
> https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing
Thank you so much !!!
