### ISSUE TITLE
Parameters for reproducing Figure 10.

### ISSUE THREAD

**Issue by giles-shaw** [wuhuikai/GP-GAN#32]
Hi - thanks for making an implementation of your work available. Could you share the CLI input arguments that were used for creating the bear/beach example from Figure 10 please? 
Using the images from [here](https://github.com/wuhuikai/DeepJS/tree/master/images/blending_mask), I haven't been able to obtain comparable results with the default parameter settings. I can reproduce the results in `images/test_images` correctly with the default params.  Thanks in advance!

**Comment by wuhuikai** [comment]
Try to tune `--color_weight`, I forgot the exact value, maybe 0.5

**Comment by thiagoribeirodamotta** [comment]
Hi, I've been struggling too when generating the bear/beach example. Just passing the src, dst and mask images generates the following error:
`ValueError: could not broadcast input array from shape (301,400,3) into shape (639,1024,3)`

Also, how to tell the script where the bear should be placed?

I was also unable to run the sample "Image Blending without Mask". How could I test this script?

**Comment by wuhuikai** [comment]
1. create an image with shape `(639,1024,3)` filled with zeros
2. put the bear on the above image with desired location
3. run the script
