### ISSUE TITLE
Google drive access problem 

### ISSUE THREAD

**Issue by aidotayyy** [wuhuikai/GP-GAN#33]
When downloading the pre training weight file, you need to access Google drive

Prompt: you do not have permission. Can you authorize access

**Comment by wuhuikai** [comment]
https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing

**Comment by aidotayyy** [comment]
thank you much!
admirable work!

**Comment by zheng325** [comment]
你好，国内谷歌下载不了，能不能提供百度云文件？十分感谢！
