### ISSUE TITLE
Transient Attributes Dataset link not working

### ISSUE THREAD

**Issue by ashishdevo28** [wuhuikai/GP-GAN#34]
Hey there, 
I am studying your repo, I just cross that link here for Transient Attributes Dataset not working.
"Download Transient Attributes Dataset [here](http://transattr.cs.brown.edu/files/aligned_images.tar)."

**Comment by wuhuikai** [comment]
Please refer to this link: http://transattr.cs.brown.edu/

**Comment by wuhuikai** [comment]
Please refer to this link: http://transattr.cs.brown.edu/
