### ISSUE TITLE
Loading pre-trained models..

### ISSUE THREAD

**Issue by mshinp** [wuhuikai/GP-GAN#35]
Hi, 

Thanks for sharing your fantastic work!
I'm trying to test your code, but faced an error when I loaded your pre-trained models.
After reading the previous issues regarding the access of your pre-trained models, I downloaded 'realismCNN_all_iter3.npz' files
on https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing

1. Is realismCNN_all_iter3.npz correct file?
    If so, is it supervised one or unsupervised one?
    Actually I'm facing an error message as below, at line 66, 'serializers.load_npz(args.g_path, G)'
    ** KeyError: 'encoder/0/W is not a file in the archive'

2. If it's incorrect file, could you share the correct files again?

Thanks in advance!

**Comment by wuhuikai** [comment]
It's the wrong model, please see [here](https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing).

**Comment by mshinp** [comment]
It works, thanks a lot!
