### ISSUE TITLE
Hi, Thank you for your work.I just want to ask something when I run your code for my work it gave me nothing and it just stuck here like this.

### ISSUE THREAD

**Issue by noreenanwar** [wuhuikai/GP-GAN#37]
python run_gp_gan.py --image_size 640 --src_image im2.jpg --dst_image im1.jpg --mask_image mask_screenshot_05.09.2022.png --blended_image images/test_images/result.jpg                          
Input arguments:
        nef: 64
        ngf: 64
        nc: 3
        nBottleneck: 4000
        ndf: 64
        image_size: 640
        color_weight: 1
        sigma: 0.5
        gradient_kernel: normal
        smooth_sigma: 1
        supervised: True
        nz: 100
        n_iteration: 2
        gpu: 0
        g_path: models/blending_gan.npz
        unsupervised_path: models/unsupervised_blending_gan.npz
        list_path: 
        result_folder: blending_result
        src_image: im2.jpg
        dst_image: im1.jpg
        mask_image: mask_screenshot_05.09.2022.png
        blended_image: images/test_images/result.jpg

I waited for so long and I didn't,t get output result

**Comment by wuhuikai** [comment]
Please provide the info after you kill the script.

**Comment by noreenanwar** [comment]
It gives me this error however I have CUDA in my environment.

    Modules:
        cuda      : No
          -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
          -> Check your CFLAGS environment variable.
      
      ERROR: CUDA could not be found on your system.
      Please refer to the Installation Guide for details:
      https://docs-cupy.chainer.org/en/stable/install.html
      
      ************************************************************
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
??> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by noreenanwar** [comment]
I also tried to run your ipynb file I got this error.I installed Cupy accordingly.I don't know where I am wrong.Could u please tell me what I did wrong.



RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libnvrtc.so.11.2: cannot open shared object file: No such file or directory

**Comment by noreenanwar** [comment]
???
