### ISSUE TITLE
How can I implement "Image Blending w/ Mask" in the Demo with different src & dst image sizes?

### ISSUE THREAD

**Issue by jingfanke** [wuhuikai/GP-GAN#42]
I am attempting to implement the "Image Blending w/ Mask" functionality in the demo.

I have an image of an animal, a mask, and a destination background image. However, the size of the animal image and the mask does not align with the destination image.

I am using the "run_gp_gan.py" script with the "blending_gan.npz" pretrained model, but it raised an error related to the size of the images: "ValueError: could not broadcast input array from shape (333, 500, 3) into shape (453, 604, 3)".

How can I successfully implement the "Image Blending w/ Mask" in the Demo when dealing with different source and destination image sizes? Any assistance or suggestions you can provide would be greatly appreciated.

Thank you for your support!

**Comment by wuhuikai** [comment]
1. canvas = np.zeros(453, 604, 3)
2. canvas[x:x+333, y:y+500] = animal
