### ISSUE TITLE
Google Cloud disk access has been denied, can you give a link to another web disk? Your pre-training model and data are not available for download

### ISSUE THREAD

**Issue by anleleaaa** [wuhuikai/GP-GAN#44]
Google Cloud disk access has been denied, can you give a link to another web disk? Your pre-training model and data are not available for download

**Comment by wuhuikai** [comment]
https://drive.google.com/drive/folders/0Bybnpq8dvwudVjBHNWNHUmVSV28?resourcekey=0-PIycD56YyYthmbURb4VKMg&usp=sharing
