### ISSUE TITLE
How can I download the pretrained model?

### ISSUE THREAD

**Issue by CnoyZ** [wuhuikai/GP-GAN#45]
Hey! I can not download your pre-trained model from your google drive link. Could I download the pre-trained model in other ways? Thanks in advance!

**Comment by wuhuikai** [comment]
Send me a request on Google Drive.

**Comment by CnoyZ** [comment]
作者你好，我之前给你发过请求连接，然后刚刚看见我能够从你的google drive里下载了，谢谢啦~
