### ISSUE TITLE
用预训练权重运行run_gp_gan.py生成的图像和原有result图像效果不一样

### ISSUE THREAD

**Issue by 1162197376** [wuhuikai/GP-GAN#46]
作者你好。
在主页的测试案例中，用blending_gan.npz运行python run_gp_gan.py --src_image images/test_images/src.jpg --dst_image images/test_images/dst.jpg --mask_image images/test_images/mask.png --blended_image images/test_images/result.png后，生成的图像整体灰灰的，呈现出的效果较差，想问下这是什么原因呢？不知哪里出现了错误？

**Comment by wuhuikai** [comment]
请上传一下效果图

**Comment by 1162197376** [comment]
![微信图片_20231109151533](https://github.com/wuhuikai/GP-GAN/assets/46440265/1b4e323b-e8b4-4061-9b2e-7bed94023647)
![微信图片_20231109151540](https://github.com/wuhuikai/GP-GAN/assets/46440265/934556d1-29a8-4cdf-ba95-884b053039ba)
上面是原有的结果图，下面是我生成的

**Comment by 1162197376** [comment]
上面的结果图是在把--color_weight调到0.001左右生成的结果，预设的0.5生成的效果是下面这样的
![微信图片_20231109152056](https://github.com/wuhuikai/GP-GAN/assets/46440265/5e9214f9-113a-4e8d-aeb3-05a5ad141d20)

**Comment by wuhuikai** [comment]
It's strange. Is the result of GAN looking good ?

**Comment by 1162197376** [comment]
没有训练GAN，这是用源代码中的权重进行的测试结果

**Comment by Craboominable** [comment]
我也遇到了这样的结果并解决.,我这边的原因是使用新的skimage库时gaussian没有了multichannel参数,我最初运行时直接把它注释掉.但是这样会导致channel识别错误,应该用channel_axis=-1作为替代来指定,这样颜色就正常了.
