### ISSUE TITLE
requirements中的cupy没有相应匹配的版本

### ISSUE THREAD

**Issue by luojunqi011027** [wuhuikai/GP-GAN#48]
![image](https://github.com/wuhuikai/GP-GAN/assets/143194084/961739fa-3ed6-4f9e-9213-9ead91c281bb)
但当我使用其他版本的cupy会出现报错，有什么其他方法吗

**Comment by wuhuikai** [comment]
可能需要用新版本的cupy然后根据报错信息去改代码
