### ISSUE TITLE
Blending result of supervised GP-GAN

### ISSUE THREAD

**Issue by NTU-P04922004** [wuhuikai/GP-GAN#9]
Hi,

Thanks for sharing your work.

I have run the latest code and got the test result (supervised GP-GAN) like the following image:
![Result](https://github.com/wuhuikai/GP-GAN/blob/master/images/test_images/result.png)

The result looks like it does not work properly.
Is this an issue?

**Comment by wuhuikai** [comment]
I haven't tested the latest code. It shouldn't look like this.
Can you run the code in commit `9213b41005259a19c5cb9c56e598b78f1f0b9123`?

**Comment by NTU-P04922004** [comment]
> I haven't tested the latest code. It shouldn't look like this.
> Can you run the code in commit `9213b41005259a19c5cb9c56e598b78f1f0b9123`?

Just tested with commit "9213b41005259a19c5cb9c56e598b78f1f0b9123" with bad luck, got the same result.

I wonder if it is the issue of migrating to newer Chainer version.

Here is my development environment:
OS: Ubuntu 18.04
Cuda: 10.0
Chainer: 6.3

**Comment by wuhuikai** [comment]
1. In `9213b41005259a19c5cb9c56e598b78f1f0b9123` , chainer==1.24
2. What's your command to get the result?

**Comment by NTU-P04922004** [comment]
>     1. In `9213b41005259a19c5cb9c56e598b78f1f0b9123` , chainer==1.24
> 
>     2. What's your command to get the result?

I used the command described in the README.md file.

Command:
`python run_gp_gan.py --src_image images/test_images/src.jpg --dst_image images/test_images/dst.jpg --mask_image images/test_images/mask.png --blended_image images/test_images/result.png`

**Comment by wuhuikai** [comment]
Then the only issue is the version of `chainer`. I will work on this problem next week.

**Comment by wuhuikai** [comment]
Now the model can be run in test mode correctly. See [here](https://github.com/wuhuikai/GP-GAN#getting-started) for the instructions.

**Comment by NTU-P04922004** [comment]
> Now the model can be run in test mode correctly. See [here](https://github.com/wuhuikai/GP-GAN#getting-started) for the instructions.

@wuhuikai  

Thank you very much~
By the way, does the problem cause by the wrong Chainer's configure flag?

**Comment by wuhuikai** [comment]
Yes, Chainer's config doesn't have the attr `test` but `train`.
